version: '3.8'

services:
  # MongoDB database
  mongodb:
    image: mongo:latest
    container_name: eeg-mongodb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=eeg_database
    networks:
      - eeg-network

  # C# Backend API service
  backend:
    build:
      context: ./backend-csharp
      dockerfile: Dockerfile
    container_name: eeg-backend-csharp
    restart: always
    ports:
      - "5001:5000"
    depends_on:
      - mongodb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__MongoDB=mongodb://admin:password@mongodb:27017/eeg_database?authSource=admin
      - MongoDb__ConnectionString=mongodb://admin:password@mongodb:27017/eeg_database?authSource=admin
      - MongoDb__DatabaseName=eeg_database
      - JwtSettings__Secret=your_jwt_secret_key_change_this_in_production_32_chars_min
      - JwtSettings__Issuer=EegilityApi
      - JwtSettings__Audience=EegilityClient
    volumes:
      - eeg_uploads:/app/uploads
      - eeg_logs:/app/logs
    networks:
      - eeg-network

  # React Frontend web application
  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    container_name: eeg-frontend-react
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000/api
    networks:
      - eeg-network

  # Python service for EEG processing and ML
  eeg-processor:
    build:
      context: ./eeg-processor
      dockerfile: Dockerfile
    container_name: eeg-processor
    restart: always
    depends_on:
      - backend
    volumes:
      - eeg_uploads:/app/data
      - ./eeg-processor:/app
      - /app/__pycache__
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/eeg_database?authSource=admin
      - DATA_DIR=/app/data
    networks:
      - eeg-network

networks:
  eeg-network:
    driver: bridge

volumes:
  mongodb_data:
  eeg_uploads:
  eeg_logs: